security:
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost:      13

    providers:
        in_memory:
            memory:
                users:
                    admin:
                        password: $2y$13$2RU6ndETgCLHuoRxQhpYsuwWnGHa5L2VXoNYHdkSjxY3Sgop0UICi
                        roles: [ 'ROLE_ADMIN' ]

    firewalls:
        admin_secured_area:
            pattern:    ^/admin/
            http_basic:
                realm: "Secured Admin Area"

    access_control:
        - { path: ^/admin/, roles: ROLE_ADMIN }